apply plugin: 'liberty'
apply plugin: 'war'

version '0.0.1-SNAPSHOT'
group 'liberty.gradle.test.app'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        maven {
            url = 'https://central.sonatype.com/repository/maven-snapshots/'
        }
    }
    dependencies {
        classpath "io.openliberty.tools:liberty-gradle-plugin:4.0.2"
    }
}


repositories {
    mavenCentral()
}

dependencies {
     // provided dependencies
     compileOnly 'javax.servlet:javax.servlet-api:3.1.0'
     compileOnly 'org.eclipse.microprofile:microprofile:5.0'
     
     // test dependencies
     testImplementation 'org.junit.jupiter:junit-jupiter:5.8.1' 
     testImplementation 'commons-httpclient:commons-httpclient:3.1'

}

liberty {
    server{
        verifyAppStartTimeout = 150
    }
}

tasks.named('clean').configure { dependsOn 'libertyStop' }
