source.. = src/
output.. = bin/
bin.includes = about.html,\
               epl-v20.html,\
               icons/,\
               libs/,\
               META-INF/,\
               plugin.xml,\
               .options,\
               .
